import { Navbar } from "@/components/ui/Navbar"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import React, { useState } from "react"
import { Header } from "@/components/ui/Header"

const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" relative">
          <div className=" absolute w-full">
            <Header />
          </div>
        </div>
        {children}
        <div className=" fixed bottom-0 w-full">
          <Navbar />
        </div>
      </body>
    </html>
  )
}
